spring.application.name=taxi_brousse

# server.servlet.encoding.charset=UTF-8
# server.servlet.encoding.enabled=true
# server.servlet.encoding.force=true

server.port=8081

#logging.level.com.gestion=DEBUG
#logging.level.org.springframework.web=DEBUG

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

server.servlet.session.timeout=43200

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE

# Configuration pour les ressources statiques
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**


spring.datasource.url=jdbc:postgresql://localhost:5432/taxi_brousse_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true